spring:
  mvc:
    log-request-details: true
management:
  endpoint:
    env:
      show-values: always
    configprops:
      show-values: always
    health:
      show-details: always
      show-components: always
  endpoints:
    web:
      exposure:
        include: '*'
  httpexchanges:
    recording:
      enabled: true

routing:
  postgres:
    consumer: "google-storage://loggkamel-dev-postgresql-consumer?deleteAfterRead=false&exceptionHandler=#gcpConsumerPollingExceptionHandler&includeBody=false"
    invalid-message: "loggkamel-dev-postgresql-invalid-message"
    invalid-message-routing: ${routing.postgres.consumer}
  packet:
    bucket: "google-storage://loggkamel-dev-logglines?deleteAfterRead=false&exceptionHandler=#gcpConsumerPollingExceptionHandler"
    invalid-message: "loggkamel-dev-logglines-invalid-message"
    invalid-message-routing: ${routing.loggline.bucket}

debug: false

