management:
  info:
    git:
      mode: simple
  observations:
    annotations:
      enabled: true
  health:
    ssl:
      enabled: false
    ping:
      enabled: false
    diskspace:
      enabled: false
  endpoints:
    web:
      base-path: /monitoring
      exposure:
        include: health,info,prometheus

spring:
  threads:
    virtual:
      enabled: true
  application:
    name: loggkamel
  datasource:
    url: ${db.jdbc.url}
    username: ${db.username}
    password: ${db.password}
    hikari:
      connection-timeout: 5000
      max-lifetime: 1200000
      idle-timeout: 600000
      connection-test-query: SELECT 1
      maximum-pool-size: ${db.poolsize}

logging:
  level:
    org.hibernate.orm.connections.pooling: WARN

no.nav.security.jwt:
  issuer:
    azuread:
      discovery-url: ${azure.app.well.known.url}
      accepted_audience: ${azure.app.client.id}
  client:
    registration:
      entra-proxy:
        token-endpoint-url: ${azure.openid.config.token.endpoint}
        grant-type: client_credentials
        scope: ${entra-proxy.scope}
        authentication:
          client-id: ${azure.app.client.id}
          client-jwk: ${azure.app.jwk}
          client-auth-method: private_key_jwt

entra-proxy:
  scope: "api://${nais.cluster.type}-gcp.sikkerhetstjenesten.entra-proxy/.default"

springdoc:
  swagger-ui:
    oauth:
      client-id: ${azure.app.client.id}
    csrf:
      enabled: true