no.nav.security.jwt:
  issuer:
    azuread:
      discoveryurl: http://localhost:8080/default/.well-known/openid-configuration
      accepted_audience: client id
    issuer1:
      discoveryurl: http://localhost:${mock-oauth2-server.port}/issuer1/.well-known/openid-configuration
      accepted_audience: someaudience
  client:
    registration:
      entra-proxy:
        token-endpoint-url: http://test.endpoint.blah
        grant-type: client_credentials
        scope: ${ENTRA_PROXY_SCOPE}
        authentication:
          client-id: ${AZURE_APP_CLIENT_ID}
          client-secret: blah
          client-auth-method: client_secret_basic

entra-proxy:
  scope: "api://${nais.cluster.type}-gcp.sikkerhetstjenesten.entra-proxy/.default"
