
spring:
  mvc:
    log-request-details: true
management:
  endpoint:
    env:
      show-values: always
    configprops:
      show-values: always
    health:
      show-details: always
      show-components: always
  endpoints:
    web:
      exposure:
        include: '*'
  httpexchanges:
    recording:
      enabled: true

routing:
  root: "google-storage://loggkamel-dev"
#  fallback:
#    invalid-message: "${routing.root}-fallback-invalid-message/"
#  postgres:
#    consumer: "${routing.root}-postgres-consumer/"
#    dead-letter: "${routing.root}-postgres-deadletter/"
#    invalid-message: "${routing.root}-postgres-invalid-message/"
#  loggline:
#    queue:
#      read: "${routing.root}-logglines/"
#      write: "${routing.root}-logglines/"
#    dead-letter: "${routing.root}-logglines-deadletter/"
#    invalid-message: "${routing.root}-logglines-invalid-message/"

debug: false