#TODO: move into env-specific configurations, including env-specific addresses
ENTRA_PROXY_BASE_URL: https://entraproxy.intern.dev.nav.no

logging:
  level:
    root: info

management:
  endpoint:
    env:
      show-values: always
    configprops:
      show-values: always
    health:
      show-details: always
      show-components: always
  endpoints:
    web:
      exposure:
        include: '*'