routing:
  postgres:
    consumer: "google-storage://loggkamel-prod-postgresql-consumer"
    dead-letter: "google-storage://loggkamel-prod-postgresql-deadletter"
    invalid-message: "google-storage://loggkamel-prod-postgresql-invalid-message"
  loggline:
    bucket: "google-storage://loggkamel-prod-logglines"