# TODO: remove this once can use env-specific configuration
spring:
  mvc:
    log-request-details: true
management:
  endpoint:
    env:
      show-values: always
    configprops:
      show-values: always
    health:
      show-details: always
      show-components: always
  endpoints:
    web:
      base-path: /monitoring
      exposure:
        include: '*'
  httpexchanges:
    recording:
      enabled: true

logging:
  level:
    root: info

#TODO: remove this once have spring profiles working
ENTRA_PROXY_BASE_URL: https://entraproxy.intern.dev.nav.no