no.nav.security.jwt:
  issuer:
    issuer1:
      discoveryurl: http://localhost:${mock-oauth2-server.port}/issuerId/.well-known/openid-configuration
      accepted_audience: someaudience
  client:
    registration:
      entra-proxy:
        token-endpoint-url: http://example.com
        grant-type: client_credentials
        scope: some-scope
        authentication:
          client-id: testclient
          client-secret: testsecret
          client-auth-method: client_secret_basic

routing:
  postgres:
    consumer: "file:src/main/resources/files"
    producer: "file:src/main/resources/files/output/?fileExist=Append"
    dead-letter: "file:src/main/resources/files/output/dead-letter?fileExist=Append"
    invalid-message: "file:src/main/resources/files/output/invalid-messages?fileExist=Append"

entra-proxy:
  scope: "api://${nais.cluster.type}-gcp.sikkerhetstjenesten.entra-proxy/.default"
