routing:
  postgres:
    consumer: "google-storage://loggkamel-ingress-pg-prod"
    dead-letter: "google-storage://loggkamel-pg-dead-letter-prod"
    invalid-message: "google-storage://loggkamel-invalid-message-pg-prod"