
spring:
  mvc:
    log-request-details: true
management:
  endpoint:
    env:
      show-values: always
    configprops:
      show-values: always
    health:
      show-details: always
      show-components: always
  endpoints:
    web:
      exposure:
        include: '*'
  httpexchanges:
    recording:
      enabled: true

routing:
  fallback:
    invalid-message: "google-storage://loggkamel-dev-fallback-invalid-message"
  postgres:
    consumer: "google-storage://loggkamel-dev-postgresql-consumer?deleteAfterRead=true"
    dead-letter: "google-storage://loggkamel-dev-postgresql-deadletter"
    invalid-message: "google-storage://loggkamel-dev-postgresql-invalid-message"
  loggline:
    bucket: "google-storage://loggkamel-dev-logglines?deleteAfterRead=true"
    dead-letter: "google-storage://loggkamel-dev-logglines-deadletter"
    invalid-message: "google-storage://loggkamel-dev-logglines-invalid-message"

debug: false