CREATE TABLE pull_rerun_required
(
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created         TIMESTAMP    NOT NULL DEFAULT NOW(),
    updated         TIMESTAMP    NOT NULL DEFAULT NOW(),
    oversikt_id     BIGINT       NOT NULL REFERENCES oversikt (id),
    pull_start_date DATE         NOT NULL,
    pull_end_date   DATE         NOT NULL,
    failure_reason  VARCHAR(1000),
    resolved        BOOLEAN      NOT NULL DEFAULT false
);

CREATE INDEX idx_pull_rerun_required_oversikt_id ON pull_rerun_required (oversikt_id);

CREATE INDEX idx_pull_rerun_required_unresolved ON pull_rerun_required (resolved) WHERE resolved = false;

-- A given task may only have one unresolved rerun entry per date range, so that repeated failures for the same
-- range update the existing entry instead of growing the table without bound
CREATE UNIQUE INDEX idx_pull_rerun_required_unique_unresolved_range
    ON pull_rerun_required (oversikt_id, pull_start_date, pull_end_date) WHERE resolved = false;

CREATE OR REPLACE FUNCTION set_pull_rerun_required_updated_timestamp()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated = NOW();
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS trg_pull_rerun_required_set_updated ON pull_rerun_required;

CREATE TRIGGER trg_pull_rerun_required_set_updated
BEFORE UPDATE ON pull_rerun_required
FOR EACH ROW
EXECUTE FUNCTION set_pull_rerun_required_updated_timestamp();
