CREATE TYPE dbms AS ENUM ('PostgreSQL', 'Oracle', 'DB2', 'IMS');

CREATE TABLE oversikt
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created     TIMESTAMP DEFAULT NOW(),
    updated     TIMESTAMP DEFAULT NOW(),
    naisteam    VARCHAR(100) NOT NULL,
    teknologi   dbms,
    dbname      VARCHAR(100) NOT NULL,
    okonomi     boolean DEFAULT false,
    arkiv       boolean DEFAULT false,
    personvern  boolean DEFAULT false,
    fiksa       boolean DEFAULT false
);