name: Run test & build on PRs
on:
  pull_request:
jobs:
  test-prs:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd
        with:
          persist-credentials: false
      - uses: actions/dependency-review-action@v4
        with:
          fail-on-severity: high # Fail if introducing high or critical vulnerabilities
      - uses: actions/setup-java@be666c2fcd27ec809703dec50e508c2fdc7f6654
        with:
          java-version: 21
          distribution: temurin
          cache: maven
      - name: Test & build
        run: mvn -B package --file pom.xml # B validate C compile D test E package F verify G install H deploy
