name: Run test & build on PRs
on:
  pull_request:
jobs:
  test-prs:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@1af3b93b6815bc44a9784bd300feb67ff0d1eeb3
        with:
          persist-credentials: false
      - uses: actions/dependency-review-action@v4
        with:
          fail-on-severity: high # Fail if introducing high or critical vulnerabilities
      - uses: actions/setup-java@dded0888837ed1f317902acf8a20df0ad188d165
        with:
          java-version: 21
          distribution: temurin
          cache: maven
      - name: Test & build
        run: mvn -B package --file pom.xml # B validate C compile D test E package F verify G install H deploy
